HELP_MESSAGE = (
    f"To set a game use !set {{game}} and replace game with the following:\n"
    f"Magic the Gathering = mtg\n"
    f"Dungeons & Dragons = dnd\n"
    f"Star Wars: Edge of the Empire = edge\n"
    f"Example: !set mtg\n"
    f"\n"
    f"Use `/r` to roll.  \n"
    "You can roll multiple dice, add modifiers etc. to your rolls examples below and roll with advantage / "
    "disadvantage (D&D term):\n "
    "- `/r 2d6`\n"
    "- `/r 1d8 + 1d6`\n"
    "- `/r 1d20 + 7`\n"
    "- `/r 2d20kh1 + 7` Roll keeping the highest result then adding 7\n"
    "- `/r 2d20kl1 + 8` Roll keeping the lowest result then adding 8\n"
    "- `/r 2d8*2 + 2` Roll 2d8 times the result by 2 and then add 2\n"
    "\n"
    "Basic calculation can be done by using `/c`: adding, subtracting, multiplication, division, and brackets \n"
    "- `/c (5 + 3)*7`"
)
