HELP_MESSAGE = (
    f"Use `/r` to roll.  \n"
    "You can roll multiple dice, add modifiers etc. to your rolls examples below and roll with advantage / "
    "disadvantage (D&D term):\n "
    "- `/r 2d6`\n"
    "- `/r 1d8 + 1d6`\n"
    "- `/r 1d20 + 7`\n"
    "- `/r 2d20kh1 + 7` Roll keeping the highest result then adding 7\n"
    "- `/r 2d20kl1 + 8` Roll keeping the lowest result then adding 8\n"
    "- `/r 2d8*2 + 2` Roll 2d8 times the result by 2 and then add 2\n"
    "\n"
    "To send your result via a direct message you can prefix your command with `!DM ` e.g `!DM /r d20`\n"
    "To make the bot hide your roll in the current channel you can prefix your command with `!hide` e.g `!hide /help`\n"
    "\n"
    "To search the SRD use `/s` followed by what you want to search:\n"
    "- `/s fireball`\n"
    "\n"
    "To search for a Magic the Gathering Card surround the card name with double square brackets:\n"
    "`[[lightning bolt]]`\n"
    "\n"
    "To flip a coin use `/flip`. You can flip a set amount of coins by providing a number: `/flip 6`\n"
    "If you want to flip until heads or tails appears: `/flip until heads` or `/flip until tails`\n"
    "If you want to flip using the rules Krark's Thumb provides: `/flip until heads with thumb`\n"
    "\n"
    "Basic calculation can be done by using `/c`: adding, subtracting, multiplication, division, and brackets \n"
    "- `/c (5 + 3)*7`\n"
    "\n"
    "To roll using edge dice you use `/r` like normal but using the dice_legacy name instead:\n"
    "`/r 2fd + 2sbd`\n"
    "Boost Die = bd\n"
    "Set Back Die = sbd\n"
    "Difficulty Die = dd\n"
    "Proficiency Die = pd\n"
    "Challenge Die = cd\n"
    "Force Die = fd\n"
    "Ability Die = ad"
)
